### ISSUE TITLE
Disable color doesn't remove the color set commands

### ISSUE THREAD

**Issue by fex95** [dl9rdz/rdz-si4463-test#1]
The `Vk` command simply sets the color to default. The commands continue to be sent. 
Here is a log of it:
[COM3_2024_03_20.10.59.36.621.txt](https://github.com/dl9rdz/rdz-si4463-test/files/14695141/COM3_2024_03_20.10.59.36.621.txt)

In the version currently used for testing, the following lines have been changed to prevent the color commands from being sent.
https://github.com/dl9rdz/rdz-si4463-test/blob/385a5c8e423cb18ae4c821b3b5af93ddc3cc2028/Test/src/logger.cpp#L46-L52

```
        if( type & logmask ) {
			char buf[256];
			if(useColor) 
				Serial.print( color(type) );
			vsnprintf( buf, 256, format, args );
			Serial.print( buf );
			if(useColor) 
				Serial.print( defcol );
        }
```

**Comment by dl9rdz** [comment]
thanks, fixed.
